name: Build and Deploy AsmNeGym

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build . -t my-application

      - name: Run Docker Container and Make Build
        run: |
          docker run --name my-app -v .:/src my-application make compile

      - name: Copy Build Directory
        run: docker cp my-app:/src/build ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build