name: Build and Deploy AsmNeGym to github pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Build and start containers using Docker Compose
        run: docker-compose up --build -d

      - name: Copy build directory from Container
        run: |
          docker cp $(docker-compose ps -q app):/src/build ./build
        if: success()

      - name: Shutdown Docker Compose services
        run: docker-compose down

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
